name: Extensions
run-name: "${{ github.event_name == 'push' && format('Publish: {0}', github.event.head_commit.message) || (github.event_name == 'pull_request' && format('Check: {0}', github.event.pull_request.title) || github.event_name == 'workflow_dispatch' && format('Manual: {0} {1}', inputs.command, inputs.paths) || format('Event: {0}', github.event_name) ) }}"

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Extensions to update (comma-separated relative paths for extensions) or ("extensions/**"" to execute on all possible subdirectories)'
        required: true
      command:
        description: "Ray CLI command to run (build | publish)"
        default: "build"
        required: true
        type: choice
        options:
          - build
          - publish
      cli_version:
        description: 'CLI Version (optional, eg. "1.0.0")'
        required: false
  pull_request:
    paths:
      - "/**"
    branches: [main, master]
  push:
    paths:
      - "/**"
    branches: [main, master]

jobs:
  extensions_build_publish:
    if: github.repository == 'raycast-jp/amaterasu'
    name: "${{ github.event_name == 'push' && 'Publish' || (github.event_name == 'pull_request' && 'Check' || github.event_name == 'workflow_dispatch' && inputs.command || github.event_name ) }}"
    runs-on: macos-14
    steps:
      - name: Setup Xcode
        uses: raycast/github-actions/setup-xcode@xcode-15.4.x
      - uses: actions/checkout@v4
        with:
          path: github_utils
          sparse-checkout: |
            .github
      - name: Cleanup github_utils
        run: |
          rm -rf ${{ github.workspace }}/github_utils
      - name: Run Ray CLI
        id: ray_cli
        uses: raycast/github-actions/ray@v1.16.0
        with:
          access_token: "${{ secrets.RAYCAST_CLI_ACCESS_TOKEN }}"
          command: "${{ github.event.inputs.command }}"
          paths: "${{ github.event.inputs.paths }}"
          cli_version: "${{ github.event.inputs.cli_version }}"
          allow_owners_only_for_extensions: "${{ steps.allow_owners_only_for_extensions.outputs.value }}"
